name: Is It Fork
on:
  workflow_dispatch: {}
jobs:
  fork-or-not:
    runs-on: ubuntu-latest
    steps:
      - name: Repository is a fork
        if: github.event.repository.fork
        run: |
          echo "This repo is a fork"
      - name: Repository is NOT a fork
        if: ${{ ! github.event.repository.fork }}
        run: |
          echo "This repo is NOT a fork"
