name: Two
on:
  push: {}
jobs:
  Wait-for-images:
    runs-on: ubuntu-latest
    outputs:
      conclusion: ${{ steps.wait.outputs.conclusion }}
    steps:
      - name: Wait for push.yml to complete
        uses: netcracker/qubership-workflow-hub/actions/wait-for-workflow@3e428f45132119ce49d90f3770a45d4fe1d1078d  # v2.0.4
        id: wait
        with:
          workflow: one.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
          poll-interval: 20
  Two-success:
    needs: Wait-for-images
    if: ${{ needs.Wait-for-images.outputs.conclusion }} == 'success'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Success!"
          echo "${{ needs.Wait-for-images.outputs.conclusion }} == 'success'"
  Two-fail:
    needs: Wait-for-images
    if: ! (${{ needs.Wait-for-images.outputs.conclusion }} == 'failure')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Success!"
          echo "${{ needs.Wait-for-images.outputs.conclusion }} != 'success'"
